#include "../headers/window_size.h"

const int ORIGINAL_WINDOWS_WIDTH=600;
const int ORIGINAL_WINDOWS_HEIGHT=600;
int WINDOWS_WIDTH=ORIGINAL_WINDOWS_WIDTH;
int WINDOWS_HEIGHT=ORIGINAL_WINDOWS_HEIGHT;
